version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000
      - LOCAL_EXCEL_PATH=/data/database.xlsx
    volumes:
      - ./backend:/app
      - ./database.xlsx:/data/database.xlsx
    command: python main.py
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
